version: '1.0'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - sternx-mongo:/data/db
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - '5672:5672'

volumes:
  sternx-mongo: 
